CREATE DATABASE ${DB_DATABASE};

\connect ${DB_DATABASE};

DROP TABLE IF EXISTS emails;
DROP TABLE IF EXISTS phones;


CREATE TABLE emails (id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, email VARCHAR(30));
CREATE TABLE phones (id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, phone VARCHAR(20));

INSERT INTO emails VALUES ('test@mail.ru', 'alyona1234@gmail.net');
INSERT INTO phones VALUES ('+79012345677', '+79999992233');
